# Build settings
# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
incremental: false

plugins: [jekyll-paginate]

# Site settings
title: "Garima Singh"
description: My Thoughts and Know-hows

email: igarimasingh@gmail.com
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/header.jpg"

name: 'Garima Singh'
author: 'Garima Singh'
author_image: "/assets/images/author1.jpg"

paginate:	5

url: "http://singhgarima.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
    - icon:	twitter
      url:	https://twitter.com/ssgarima
      desc: Follow me on twitter
      share_url: http://twitter.com/share
      share_title: ?text=
      share_link: "&amp;url="

    # - icon:	facebook
    #    url:	https://facebook.com/igarimasingh
    #    desc: Connect with me facebook
    #    share_url: //www.facebook.com/sharer.php
    #    share_title: ?t=
    #    share_link: "&amp;u="

    - icon:	github
      url:	https://github.com/singhgarima
      desc:	Fork me on github
      share_url:
      share_title:
      share_link:

    - icon:	linkedin
      url:	https://www.linkedin.com/in/igarimasingh
      desc:	Connect with me on LinkedIn
      share_url:
      share_title:
      share_link:

# Handling Reading
safe:                false
exclude:             ["Gemfile", "Gemfile.lock", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:          [".git"]
encoding:            "utf-8"
markdown_ext:        "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: true