# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Garima Singh"
description: My Thoughts and Know-hows

email: igarimasingh@gmail.com
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Garima Singh'
author: 'Garima Singh'
author_image: "/assets/images/author1.jpg"

paginate:	5

url: "" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
    - icon:	twitter
      url:	https://twitter.com/ssgarima
      desc: Follow me on twitter
      share_url: http://twitter.com/share
      share_title: ?text=
      share_link: "&amp;url="

    # - icon:	facebook
    #    url:	https://facebook.com/igarimasingh
    #    desc: Connect with me facebook
    #    share_url: //www.facebook.com/sharer.php
    #    share_title: ?t=
    #    share_link: "&amp;u="

    - icon:	github
      url:	https://github.com/singhgarima
      desc:	Fork me on github
      share_url:
      share_title:
      share_link:

    - icon:	linkedin
      url:	https://www.linkedin.com/in/igarimasingh
      desc:	Connect with me on LinkedIn
      share_url:
      share_title:
      share_link:
